name: Docker Build

on:
  push:
    branches:
      - "main"
    paths:
      - Dockerfile
      - docker.version

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                persist-credentials: false

            - name: Read version
              uses: juliangruber/read-file-action@v1
              id: docker_version
              with:
                path: docker.version
        
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
        
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: .
                platforms: linux/amd64,linux/arm64
                push: true
                tags: yuvalpress/aws-lambda-tesseract:latest, yuvalpress/aws-lambda-tesseract:${{ steps.docker_version.outputs.content }}